#!/usr/bin/env python3
"""V2 host bootstrap: IPs + default routes + nc-mock services + traffic crons.

Pushes bootstrap script to each Alpine host via GNS3 console (telnet).
16 hosts: 8 zones × 2 hosts. Each host gets:
  - eth0 IP + default route via its zone's LEAF SVI
  - sshd (root, no pw)
  - zone-specific service (nc-mock banner OR pg-mock SQL responder)
  - cron-driven east-west traffic per V2 §8.2
"""
import pexpect, time, base64, sys

# zone → (subnet_prefix, gateway, leaf, vlan, service_port, service_kind)
ZONES = {
    "WEB":          ("10.1.100", "10.1.100.1", "LEAF-1", 100,   80, "banner"),
    "DB-OLTP":      ("10.1.200", "10.1.200.1", "LEAF-1", 200, 5432, "pg-mock"),
    "APP-CORE":     ("10.2.100", "10.2.100.1", "LEAF-2", 100, 8090, "banner"),
    "MGT":          ("10.2.50",  "10.2.50.1",  "LEAF-2", 300,    0, "none"),
    "APP-GW":       ("10.3.100", "10.3.100.1", "LEAF-3", 100, 8080, "banner"),
    "DB-ANALYTICS": ("10.3.200", "10.3.200.1", "LEAF-3", 200, 5432, "pg-mock"),
    "WORKER":       ("10.4.100", "10.4.100.1", "LEAF-4", 100, 8082, "banner"),
    "MONITORING":   ("10.4.200", "10.4.200.1", "LEAF-4", 200, 9090, "banner"),
}

# host → (zone, console_port, last_ip_octet)
HOSTS = {
    # v1 existing (will be re-bootstrapped, were wiped)
    "Alpine-Linux-1":  ("WEB",          5008, 10),
    "Alpine-Linux-2":  ("DB-OLTP",      5011, 10),
    "Alpine-Linux-3":  ("APP-CORE",     5014, 10),
    "Alpine-Linux-5":  ("MGT",          5016, 10),
    # v2 new
    "WEB-2":           ("WEB",          5029, 11),
    "DB-OLTP-2":       ("DB-OLTP",      5031, 11),
    "APP-CORE-2":      ("APP-CORE",     5033, 11),
    "MGT-2":           ("MGT",          5035, 11),
    "APP-GW-1":        ("APP-GW",       5037, 10),
    "APP-GW-2":        ("APP-GW",       5039, 11),
    "DB-ANALYTICS-1":  ("DB-ANALYTICS", 5041, 10),
    "DB-ANALYTICS-2":  ("DB-ANALYTICS", 5043, 11),
    "WORKER-1":        ("WORKER",       5045, 10),
    "WORKER-2":        ("WORKER",       5047, 11),
    "MONITORING-1":    ("MONITORING",   5049, 10),
    "MONITORING-2":    ("MONITORING",   5051, 11),
}


def gen_bootstrap(hostname, zone, ip, gateway, svc_port, svc_kind):
    """Generate /root/bootstrap.sh content for an Alpine host."""
    parts = [
        "#!/bin/sh",
        "# V2 host bootstrap - auto-generated by v2-bootstrap-hosts.py",
        "set -e",
        f"echo '=== bootstrap {hostname} (zone={zone} ip={ip}) ===' ",
        "",
        "# 1) network",
        f"ip link set eth0 up",
        f"ip addr add {ip}/24 dev eth0 2>/dev/null || true",
        f"ip route add default via {gateway} 2>/dev/null || true",
        f"hostname {hostname}",
        "",
        "# 2) Alpine repos + packages",
        "grep -q dl-cdn /etc/apk/repositories 2>/dev/null || cat > /etc/apk/repositories <<EOF",
        "https://dl-cdn.alpinelinux.org/alpine/v3.23/main",
        "https://dl-cdn.alpinelinux.org/alpine/v3.23/community",
        "EOF",
        "apk update 2>&1 | tail -1",
        "apk add --no-cache socat busybox-extras 2>&1 | tail -1",
    ]
    # 4) per-zone service
    if svc_kind == "banner" and svc_port > 0:
        parts += [
            "",
            f"# 4) banner service on :{svc_port}",
            f"cat > /tmp/banner-{svc_port} <<EOF",
            f"HTTP/1.0 200 OK",
            f"Server: {hostname}-{svc_port}",
            f"Content-Type: text/plain",
            f"",
            f"{hostname} ready (zone={zone} port={svc_port})",
            f"EOF",
            f"nohup sh -c 'while true; do nc -l -p {svc_port} < /tmp/banner-{svc_port} 2>/dev/null; done' >/dev/null 2>&1 &",
        ]
    elif svc_kind == "pg-mock":
        parts += [
            "",
            "# 4) pg-mock SQL responder on :5432",
            "cat > /usr/local/bin/db-reply.sh <<'REPLY'",
            "#!/bin/sh",
            "IFS='' read -t 1 line",
            "case \"$line\" in",
            "    *JOIN*|*'SELECT *'*)",
            "        i=0",
            "        while [ $i -lt 80 ]; do",
            "            printf 'row_%03d | user=user_%03d | order=ORD%05d | data=lorem_ipsum_dolor_sit_amet_padding\\n' $i $i $((i*7+1000))",
            "            i=$((i+1))",
            "        done",
            "        ;;",
            "    *)",
            "        printf 'PG_OK row_count=42 ts=%s\\n' \"$(date +%s)\"",
            "        ;;",
            "esac",
            "REPLY",
            "chmod +x /usr/local/bin/db-reply.sh",
            "nohup socat TCP-LISTEN:5432,reuseaddr,fork EXEC:/usr/local/bin/db-reply.sh,pipes >/dev/null 2>&1 &",
        ]
    # 5) per-zone traffic generators (cron)
    cron_lines = []
    if zone == "WEB":
        # WEB → APP-GW:8080 every 30s
        cron_lines.append("*/1 * * * * for i in 1 2; do echo 'GET /' | nc -w 2 10.3.100.10 8080 >/dev/null 2>&1; sleep 30; done")
    elif zone == "APP-GW":
        cron_lines.append("*/1 * * * * for i in 1 2; do echo 'fwd' | nc -w 2 10.2.100.10 8090 >/dev/null 2>&1; sleep 30; done")
    elif zone == "APP-CORE":
        cron_lines.append("*/1 * * * * for i in 1 2; do echo 'SELECT * FROM users' | nc -w 2 10.1.200.10 5432 >/dev/null 2>&1; sleep 30; done")
        cron_lines.append("*/1 * * * * for i in 1 2; do echo 'job' | nc -w 2 10.4.100.10 8082 >/dev/null 2>&1; sleep 45; done")
        cron_lines.append("*/1 * * * * for i in 1 2; do echo 'SELECT report' | nc -w 2 10.3.200.10 5432 >/dev/null 2>&1; sleep 60; done")
    elif zone == "WORKER":
        cron_lines.append("*/1 * * * * for i in 1 2; do echo 'INSERT log' | nc -w 2 10.1.200.10 5432 >/dev/null 2>&1; sleep 45; done")
    elif zone == "DB-OLTP":
        cron_lines.append("*/2 * * * * echo 'SELECT * FROM JOIN replicate' | nc -w 3 10.3.200.10 5432 >/dev/null 2>&1")
    elif zone == "MONITORING":
        cron_lines.append("*/1 * * * * for t in 10.1.100.10:80 10.3.100.10:8080 10.2.100.10:8090 10.4.100.10:8082 10.1.200.10:5432 10.3.200.10:5432; do nc -w 1 -z $(echo $t|tr : ' ') 2>/dev/null; done")
    elif zone == "MGT":
        # MGT → all:22 rotating
        cron_lines.append("*/2 * * * * for t in 10.1.100.10 10.2.100.10 10.4.100.10 10.3.100.10; do (sshpass -p '' ssh -o StrictHostKeyChecking=no -o ConnectTimeout=2 root@$t uptime 2>/dev/null || nc -w 1 -z $t 22 2>/dev/null); done")

    if cron_lines:
        parts += ["", "# 5) traffic crons"]
        parts += [f"mkdir -p /etc/crontabs"]
        for line in cron_lines:
            parts += [f"echo '{line}' >> /etc/crontabs/root"]
        parts += ["crond -L /var/log/crond.log 2>/dev/null &"]
    parts += ["", f"echo '=== bootstrap {hostname} DONE ===' "]
    return "\n".join(parts)


def push_bootstrap(hostname, console, content):
    print(f"\n========== {hostname} (:{console}) ==========")
    P = "BRDY""8> "
    c = pexpect.spawn(f"telnet 127.0.0.1 {console}", timeout=60, encoding="utf-8")
    c.send("\r"); time.sleep(0.4); c.send("\r"); time.sleep(0.4)
    i = c.expect([r"login:", r"# ", pexpect.TIMEOUT], timeout=15)
    if i == 2: print("  TIMEOUT login"); return
    if i == 0:
        c.sendline("root")
        j = c.expect([r"[Pp]assword:", r"# ", pexpect.TIMEOUT], timeout=10)
        if j == 0: c.sendline(""); c.expect(r"# ", timeout=10)
    c.sendline("PS1='BRDY''8> '"); c.expect(P, timeout=12)
    # Push script via base64 chunks (small chunks for tty safety)
    b64 = base64.b64encode(content.encode()).decode()
    c.sendline("rm -f /tmp/_bs.b64")
    c.expect(P, timeout=10)
    CHUNK = 800
    for i, off in enumerate(range(0, len(b64), CHUNK)):
        chunk = b64[off:off+CHUNK]
        op = ">" if i == 0 else ">>"
        c.sendline(f"printf '%s' '{chunk}' {op} /tmp/_bs.b64")
        c.expect(P, timeout=10)
    c.sendline("base64 -d /tmp/_bs.b64 > /root/bootstrap.sh; chmod +x /root/bootstrap.sh; wc -l /root/bootstrap.sh")
    c.expect(P, timeout=10)
    # Run it (background-ish; some apk add takes long)
    c.sendline("sh /root/bootstrap.sh 2>&1 | tail -10")
    c.expect(P, timeout=300)
    print(c.before[-400:])
    c.sendline("exit"); time.sleep(0.3)


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else "all"
    for hostname, (zone, console, octet) in HOSTS.items():
        if target != "all" and target != hostname and target != zone:
            continue
        subnet_pfx, gw, leaf, vlan, port, kind = ZONES[zone]
        ip = f"{subnet_pfx}.{octet}"
        content = gen_bootstrap(hostname, zone, ip, gw, port, kind)
        push_bootstrap(hostname, console, content)
    print("\n=== bootstrap complete ===")
